#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 30 10:29:57 2020

@author: ep9k
"""

import geopandas as gpd
import pandas as pd

#import condo_buildings_list function
MODULE_PATH = '/Users/ep9k/Desktop/BRE/BRE 2019/BRE_Condos_List/scripts/CountyFunctions.py'
MODULE_NAME = 'condo_buildings_list'
import importlib
import sys
spec = importlib.util.spec_from_file_location(MODULE_NAME, MODULE_PATH)
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module 
spec.loader.exec_module(module)

import BRE_Workflow_Functions as bwf


#1.
#import all 2019 parcels and matt's 4/20 list (which has most updated 2+ removed column)
#FOR SOME REASON, I NEED TO GO FROM THE ORIGINAL PARCELS GPKG FILE, OR ELSE 'GEOMETRY' COLUMN BECOMES CORRUPTED
all_2019_parcels = gpd.read_file('/Users/ep9k/Desktop/BRE/BRE 2019/All_Parcels_2019.gpkg')                   #228,393 parcels
matt_parcel_update_excel = pd.read_excel(r'/Users/ep9k/Desktop/master_list_2019.xlsx')
condos_list_2019 = pd.read_excel(r'/Users/ep9k/Desktop/BRE/BRE 2019/MattCondoAddressList2019.xlsx')          #3139 parcels



##drop duplicates from matt_parcel_update_excel so that I have one to many relationship between the two lists
matt_parcel_update_excel = matt_parcel_update_excel.drop_duplicates(subset='parno', keep='first')


#merge list without duplicates (matt_parcel_update_excel) to all_2019_parcels (master_list)
all_2019_parcels = all_2019_parcels.merge(matt_parcel_update_excel, how='left', left_on='parno', right_on='parno')
#THERE ARE STILL SOME DUPLICATES. Duplicates still exist in all_2019_parcels

#drop unneeded columns
columns_to_drop = ['id_0','id','altparno_x','cntyfips_x','cntyname_x','gisacres_x','gnisid','improvval_x','landval_x','legdecfull','maddpref',
                   'maddrno','maddstname','maddstr','maddstsuf','maddsttyp','mailadd_x','mapref','mcity_x','mstate_x','multistruc_x','munit','mzip_x',
                   'nparno_x','ownfrst','ownlast','ownname_x','ownname2_x','owntype','parusecd2_x','parusecode_x','parusedesc_x','parusedsc2',
                   'parval_x','parvaltype_x','presentval_x','recareano_x','recareatx_x','revdatetx','revisedate_x','reviseyear_x','saddno_x',
                   'saddpref','saddstname_x','saddstr_x','saddstsuf_x','saddsttyp_x','saledate_x','saledatetx_x','scity','siteadd_x','sourceagnt_x',
                   'sourcedate_x','sourcedatx_x','sourceref_x','sstate_x','stcntyfips_x','stfips_x','stname_x','struct_x','structno','structyear_x',
                   'subdivisio','subowntype','subsurfown','sunit','szip','transfdate_x','layer','path','geometry_y']

all_2019_parcels.drop(columns_to_drop, inplace=True, axis=1)

#rename existing columns if needed
all_2019_parcels.rename(columns = {'altparno_y': 'altparno','cntyfips_y': 'cntyfips','cntyname_y': 'cntyname','gisacres_y': 'gisacres',
                                   'improvval_y': 'improvval','landval_y': 'landval','legdecfull_y': 'ledgecfull','multistruc_y': 'multistruc',
                                   'ownname2_y': 'ownname2','parno_y': 'parno','parusecd2_y': 'parusecd2','parusecode_y': 'parusecode','parusedesc_y': 'parusedesc',
                                   'parval': 'parval','parvaltype_y': 'parvaltype','presentval_y': 'presentval','recareano_y': 'recareano',
                                   'recareatx_y': 'recareatx','revisedate_y': 'revisedate','reviseyear_y': 'reviseyear','saddno_y': 'saddno',
                                   'saddstname_y': 'saddstname','saddstr_y': 'saddstr','saddstsuf_y': 'saddstsuf','saddsttyp_y': 'saddsttyp',
                                   'saledate_y': 'saledate','saledatetx_y': 'saledatetx','sourceagnt_y': 'sourceagnt','sourcedate_y': 'sourcedate',
                                   'sourcedatx_y': 'sourcedatx','sourceref_y': 'sourceref','sstate_y': 'sstate','stcntyfips_y': 'stcntyfips','stfips_y': 'stfips',
                                   'stname_y': 'stname','struct_y': 'struct','structyear_y': 'structyear','transfdate_y': 'transfdate', 'geometry_x':'geometry',
                                   'mailadd_y':'mailadd','mcity_y':'mcity','ownname_y':'ownname','parval_y':'parval','state_y':'mstate','mzip_y':'mzip', 
                                   'siteadd_y':'siteadd','mstate_y':'mstate','nparno_x':'nparno'},
                                    inplace=True)






#2.
#Create Vacant Land Property Type

#create 'Property Type' column and populate with true/false values
all_2019_parcels['Property Type'] = all_2019_parcels['landval'] == all_2019_parcels['parval']

#change true/false values to 'Vacant Land' or no value.
all_2019_parcels.loc[(all_2019_parcels['Property Type'] == True), 'Property Type'] = 'Vacant Land'
all_2019_parcels.loc[(all_2019_parcels['Property Type'] == False), 'Property Type'] = ''

##Label others from Watauga County using parusedesc columnn. Now there are 94778 vacant land parcels (added 190 parcels)
all_2019_parcels = bwf.property_type_column(all_2019_parcels)



####START HERE FOR TROUBLESHOOTING

#3.
#Label condo buildings as 'Property Type' = 'Condo Building'
#first, read in condos list
#uses condo_buildings_list function from BRE_condos_list folder (import statements at top)
condo_building_ids = module.condo_buildings_list(condos_list_2019)



#iterate over list (condo_building_ids) and add 'Property Type' of 'Condo Building'
all_2019_parcels.loc[all_2019_parcels['parno'].isin(condo_building_ids), 'Property Type'] = 'Condo Building'
#there are now 263 condos

#build list of townhomes
townhomes_list = all_2019_parcels.loc[all_2019_parcels['parusedesc'] == 'TOWNHOUSE']
townhomes_ids = townhomes_list['parno'].tolist()

#add townhome values to 'Property Type' column
all_2019_parcels.loc[all_2019_parcels['parno'].isin(townhomes_ids), 'Property Type'] = 'Townhome'
#there are now 435 townhomes


#4.
#label residential parcels as 'property type' of Home or Home/Potentially Not Residential
all_2019_parcels = bwf.residential_parcels(all_2019_parcels)
#There are now 20903 'Homes' and 112020 'Home/Potentially Not Residential'

"""
Results after labeling all parcels with a 'Property Type'

Home / Potentially Not Residential    112020
Vacant Land                            94778
Home                                   20903
Townhome                                 435
Condo Building                           257

"""


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#  NOW START PARSING RESULTS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#


#5
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#  VACANT LAND LIST
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#make vacant land dataframe
vacant_land_df = all_2019_parcels[all_2019_parcels['Property Type'] == 'Vacant Land']

#apply filters to vacant land df (acreage and price filters)
vacant_land_df = bwf.vacant_land_filters(vacant_land_df)
#we are left with 4746 vacant land parcels



#remove undesireable zoning types from 'parusedesc' column (Watauga Only)
bad_parusedesc = ['COMMERCIAL AUXILIARY IMPROVEMENT','COMMERCIAL LAND VACANT','COMMERCIAL UNDER CONSTRUCTION','EDUCATION','EDUCATION RELIGIOUS','ELECTRIC UTILITY','GOVERNMENT','HEALTH SPA','INDUSTRIAL TRACT VACANT','RELIGIOUS','UTILITY VACANT LAND','WAREHOUSE WITH INTERIOR OFFICE SPACE']

for parusedesc in bad_parusedesc:
    vacant_land_df.drop(vacant_land_df[vacant_land_df['parusedesc'] == parusedesc].index, inplace=True)
#down to 4596 parcels


#drop owner names which are clearly commercial, industrial, etc.
bad_owner_names = ['WATAUGA COUNTY','WATAUGA BUILDING SUPPLY INC.','WATAUGA MEDICAL CENTER INC','WATAUGA OPPORTUNITIES INC.','REYNOLDS BLUE RIDGE PROP OWNERS ASSO INC','REYNOLDS BLUE RIDGE PROPERTY OWNERS ASSN','APPALACHIAN STATE UNIV FOUND,MCKINNEY ALUMNI CENTER','APPALACHIAN STATE UNIV FOUND,MCKINNEY ALUMNI CENTER','APPALACHIAN STATE UNIVERSITY FOUNDATION',
                   'BOARD OF TRUSTEES OF THE ENDOWMENT FUND ,.APPALACHIAN STATE UNIVERSITY BOARD OF T','BOARD OF TRUSTEES OF THE ENDOWMENT FUND,.APPALACHIAN STATE UNIVERSITY BOARD OF T','NORTH CAROLINA, STATE OF','STATE EMPLOYEES CREDIT UNION','STATE OF NC','STATE OF NC PROPERTY OFFICE','STATE OF NC,STATE PROPERTY OFFICE','STATE OF NORTH CAROLINA',
                   'STATE OF NORTH CAROLINA C/O STATE PROPERTY OFFICE','STATE OF NORTH CAROLINA THE','UNITED STATED OF AMERICA','UNITED STATES AGRICULTURE','UNITED STATES DEPT OF INTERIOR','UNITED STATES FOREST SERVICE','UNITED STATES OF AMERICA','NATURE CONSERVANCY','NATURE CONSERVANCY THE','NATURE CONSERVANCY, THE','NC NATURE CONSERVANCY','AVERY DEVELOPMENT CORPORATION',
                   'COUNTY OF AVERY','COUNTY OF ASHE','COUNTY OF ASHE THE','CALDWELL COUNTY','ASHE COUNTY OF','ASHE COUNTY BOARD OF EDUCATION','WATAUGA COUNTY','NC','NC DEPARTMENT OF TRANSPORTATION','CHESTER BAR OF NORTH CAROLINA','USA','OLEANDER COMPANY THE','APPALACHIAN SKI MTN INC','APPALACHIAN ADVENT CHRISTIAN ASSOCIATION','APPALACHIAN STATE UNIVERSITY',
                    'LEES MC RAE COLLEGE FIXED ASSETS COORDINATOR','LEES MC RAE COLLEGE, INC','BALD MOUNTAIN BAPTIST CHURCH INC','BALD MOUNTAIN TRUST THE (TRUSTEES)','BANNER ELK PRESBYTERIAN CHURCH','DIVINE HOPE BAPTIST CHURCH','MORAVIAN CHURCH IN AMERICA S.P.','NORTH CAROLINA DEPARTMENT OF TRANSPORTATION','FOOTHILLS CONSERVANCY OF NORTH CAROLINA','LANTANA FLORIDA CORPORATION',
                    'BLOWING ROCK REALTY & INS INC','CALDWELL REALTY','PRY REALTY LLC','WEST JEFFERSON REALTY LLC','WILBERN REALTY & INVESTMENT CO','YOUNG MEN''S CHRISTIAN ASSOCIATION','VILLAGE OF SUGAR MOUNTAIN','SUGAR MOUNTAIN RESORT INC','SOUTHERN APPALACHIAN HIGHLANDS CONSERVANCY','BLUE RIDGE CONSERVANCY','BLOWING ROCK COUNTRY CLUB','TOWN OF BLOWING ROCK',
                    'INDEPENDENCE LUMBER COMPANY INC.','JEFFERSON DEVELOPMENT CORPORATION','JENSEN HOLDINGS, INC A FLORIDA CORP.','L&S LAND CORPORATION','ELK CREEK DEVELOPMENT COMPANY OF BANNER ELK, LLC','FIRST CITIZENS BANK & TRUST COMPANY','GENTRY CONSTRUCTION COMPANY INC.','R & R BUILDERS COMPANY OF NORTH CAROLINA','R&R BUILDERS COMPANY OF NORTH CAROLINA','THE HIGHLANDER COMPANY',
                    'HIGH POINT BANK & TRUST CO SUCCESSOR TR,THE T HENRY WILSON FAMILY TRUST', 'AVERY REAL PROPERTIES, LLC','CFFC REAL ESTATE LLC','GENTRY FAMILY REAL ESTATE, LLC','GRIFFITH, E C CO REALTORS','B JOYCE HATFIELD REVOCABLE LIVING TRUST','COY BOLICK LIVING TRUST,C/O DAVID AND JULIE JONES','DODSON LIVING TRUST','DOUGLAS L MCGUIRE LIVING TRUST','GLENN SUSAN LIVING TRUST',
                    'GRACE K HUTCHINS LIVING TRUST,KILKELLY, GARY AND JOAN','GREYSTONE LIVING TRUST','HAGLER, ROSS TRUSTEE OF THE HAGLER, DOROTHY LIVING TRUST','LEMLY MINNIE C (LIVING TRUST) (1/2)','LILLIAN TURCHIN LIVING TRUST','LINDA J HODGES LIVING TRUST,HODGES, LINDA J','MARY S HORN LIVING TRUST,HORN, MARY S TR','MICHAEL M MILLER REVOCABLE LIVING TRUST','RONALD J STANLEY LIVING TRUST',
                    'STONE, HERBERT S. & BETTY W. STONE LIVING TRUST','THOMAS A BARRETT LIVING TRUST','TRIPLETT, JIM W,.JIMMY W TRIPLETT LIVING TRUST','THOMAS L GREER LIVING TRUST,THGREER, THOMAS L \TR','WILLA JEAN BROWN LIVING TRUST','WILLIAM J. WILLIAMSON, III LIVING TRUST','WILLIAM STEWART PENICK LIVING TRUST,PENICK, STEWART','BAKER ARVIL R & JOYCE G (L/E)','BARE HAZEL (L/E)',
                    'BARKER CLARA (L/E)','BLACKBURN ALENE (L/E)','BUSIC, RODNEY F. JR. & SANDRA L. L/E','CHURCH, PAUL E. JR.  ET AL L/E','DAVIS, HAROLD RANDALL & PEGGY LORAINE L/E','DILLARD GLADYS  (L/E)','DUNCAN, PETTY CHOATE L/E','GREENE HATTIE JO (L/E)','HART STEVE (L/E)','JOINES, KATHRYN L/E','LITTLE KATHLEEN (L/E)','LITTLE KATHLEEN (L/E) & MARTIN','LITTLE KATHLEEN E (L/E)',
                    'LONG CLAYTON & W G LONG (L/E)','MABE, EVERETTE J. & SHIRLEY S. L/E','MILLER ROBERT W (L/E)','REEVES, OSCAR A. L/E','ROUPE, LIZABETH R. L/E','SOPER BETTY CAROLYN (L/E)','STURGILL JEAN (L/E)','TESTERMAN CORINE D (L/E)','TUCKER, BETTY B. L/E','WAGONER, JAMES L/E','WEAVER LORETTA J (L/E)','LANGSTON, CRAIG LIFE ESTATE,JAMES, J DIANE',
                    'STORIE, MARVIN K (LIFE ESTATE),SIGMON, MARGARET E (LIFE ESTATE)','TRIVETTE, ALICE(LIFE ESTATE),TRIVETTE, BOBBY B']

for owner_name in bad_owner_names:
    vacant_land_df.drop(vacant_land_df[vacant_land_df['ownname'] == owner_name].index, inplace=True)
#down to 4200 parcels

#export Vacant land parcels to shapefile for use in PostgreSQL
vacant_land_df = gpd.GeoDataFrame(vacant_land_df, geometry='geometry')
vacant_land_df.to_file('/Users/ep9k/Desktop/vacant_land.shp')




#6
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#  HOMES LIST
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#make homes dataframe
homes_df1 = all_2019_parcels[all_2019_parcels['Property Type'] == 'Home']
homes_df2 = all_2019_parcels[all_2019_parcels['Property Type'] == 'Home / Potentially Not Residential']
homes_df = pd.concat([homes_df1, homes_df2])
#down to 132923 parcels


#These are known undesirable 'parusecode' values (Only Watauga County). I'll compile a list of these and later drop rows with these values
bad_parusedesc = [ 'AGRICULTURAL-IMPROVED' , 'AGRICULTURAL-VACANT' , 'AMBULANCE SERVICE' , 'AMERICAN LEGION/ETC' , 'AMUSEMENT PARK' , 'APARTMENT - HIGH RISE' , 
                  'APARTMENT-GARDEN (1-3 STORIES)' , 'ASPHALT PLANT' , 'AUTO DEALERSHIP' , 'AUTO SERVICE GARAGE' , 'AUXILIARY IMPROVEMENT' , 'BANK' , 
                  'BOARDING/ROOMING HOUSE' , 'BOWLING ALLEY' , 'CAR WASH (AUTOMATIC)' , 'CAR WASH (MANUAL)' , 'CEMENT MFG.' , 'CHARITABLE (ALL OTHER)' , 'CHARITABLE (HOMES)' , 
                  'CHARITABLE (HOSPITAL)' , 'CLUB HOUSE' , 'COMMERCIAL AUXILIARY IMPROVEMENT' , 'COMMERCIAL LAND VACANT' , 'COMMERCIAL UNDER CONSTRUCTION' , 'COMMUNITY SHOPPING CENTER' , 
                  'CONCRETE MFG.' , 'CONDOMINIUM (COMMON AREA)' , 'CONVENIENCE STORE' , 'COUNTRY CLUB WITHOUT GOLF COURSE' , 'DAY CARE CENTER' , 'DEPARTMENT STORE' , 
                  'DISCOUNT DEPARTMENT STORE' , 'DOWNTOWN ROW TYPE' , 'EDUCATION' , 'EDUCATION RELIGIOUS' , 'ELECTRIC UTILITY' , 'EXCLUSIONS (ALL OTHERS)' , 'EXCLUSIONS (COMMONE AREAS)' , 
                  'EXEMPTIONS (ALL OTHERS)' , 'EXEMPTIONS (CEMETERY)' , 'FAST FOOD' , 'FOOD STAND' , 'FUNERAL HOME' , 'FURNITURE MFG.' , 'GOLF COURSE' , 'GOVERNMENT' , 'HEALTH SPA' , 
                  'HOTEL HIGH RISE W/O LOUNGE OR RESTAURANT' , 'HOTEL HIGH RISE WITH LOUNGE OR RESTAURANT' , 'HOTEL LOW RISE W/O LOUNGE OR RESTAURANT' , 'INDUSTRIAL TRACT VACANT' , 
                  'LEATHER PRODUCTS MFG.' , 'LUMBER STORAGE FACILITY' ,  'MANUFACTURING/PROCESSING' , 'MEAT PACKING & SLAUGHTERHOUSE' , 'MEDICAL OFFICE' , 'METAL WORKING' , 'MINI WAREHOUSE' , 
                  'MISCELLANEOUS AMUSEMENT' ,  'MOTEL LOW RISE WITH LOUNGE OR RESTAURANT' , 'NEWSPAPER PLANT' , 'NON-EX-SCHOOL' , 'NURSING/CONVALESCENT HOME' , 'OFFICE BUILDING LOW RISE (1-4 ST)' , 
                  'OFFICE CONDOMINIUMS' , 'OFFICE/RETAIL' , 'PAR 3 GOLF COURSE' , 'PARKING (MISCELLANEOUS)' , 'REGIONAL SHOPPING MALL' , 'RELIGIOUS' , 'RESTAURANT' , 
                  'RETAIL - MULTIPLE OCCUPANCY' , 'RETAIL - SINGLE OCCUPANCY' , 'RETAIL CONDOMINIUM'  'SAVINGS INSTITUTION' , 'SERVICE STATION WITH BAYS' , 'SERVICE STATION WITHOUT BAYS' , 
                  'SKATING RINK' , 'SOCIAL/FRATERNAL HALL' , 'STONE/MINERAL QUARRY' , 'STRIP SHOPPING CENTER' , 'SUPERMARKET' , 'TELEPHONE UTILITY NEC' , 'TENNIS CLUB INDOOR' , 'TRUCK TERMINAL' , 
                  'UNSOUND COMM. STRUCTURE' , 'UTILITY VACANT LAND' , 'VETERINARY CLINIC' , 'WAREHOUSE' , 'WAREHOUSE WITH INTERIOR OFFICE SPACE' , 'WAREHOUSE-PREFABRICATED' , 'WATER AMUSEMENT' , 
                  'WOODWORKING SHOP','COMMERCIAL AUXILIARY IMPROVEMENT','COMMERCIAL LAND VACANT','COMMERCIAL UNDER CONSTRUCTION','EDUCATION','EDUCATION RELIGIOUS','ELECTRIC UTILITY','GOVERNMENT',
                  'HEALTH SPA','INDUSTRIAL TRACT VACANT','RELIGIOUS','UTILITY VACANT LAND','WAREHOUSE WITH INTERIOR OFFICE SPACE' ]


#drop rows with these parusedesc from homes_df 
for parusedesc in bad_parusedesc:
    homes_df.drop(homes_df[homes_df['parusedesc'] == parusedesc].index, inplace=True)
#drops 3540 parcels. Down to 129383 parcels


#Make list of known bad owner names from 'ownname' column
#read in bad owner names. This is instead of manually sorting at the end which is haphazard and inconsistent.
bad_owner_names = ['U S A FOREST SERVICE','UNITED COMMUNITY BANK','UNITED STATES AGRICULTURE','UNITED STATES DEPT OF INTERIOR','UNITED STATES FOREST SERVICE','UNITED STATES OF AMERICA','UNIVERSITY OF MOUNT OLIVE INC','UPPER MOUNTAIN RESEARCH STATION','USA','USA % BLUE RIDGE PARKWAY SUPT','ALLEGHANY COUNTY',
                   'ALLEGHANY COUNTY BOARD OF EDUCATION','ALLEGHANY COUNTY COURTHOUSE','ALLEGHANY MEMORIAL HOSPITAL','ALLEGHANY WELLNESS CENTER INC.','APPALACHIAN CHURCH INC','APPALACHIAN REGIONAL HEALTCARE SYS INC','APPALACHIAN SKI MTN INC','APPALACHIAN STATE UNIVERSITY','APPALACHIAN STATE UNIVERSITY FOUNDATION & ET AL',
                   'ASHE COUNTY OF','ASHE COUNTY TRANSPORTATION AUTHORITY','ASHE FEDERAL BANK','APPALACHIAN CHURCH INC','BAILEYS CAMP BAPTIST CHURCH','BALD MOUNTAIN BAPTIST CHURCH INC.','BALDWIN COMMUNITY CHURCH','BANNER ELK PRESBYTERIAN CHURCH','BEAVER CREEK CHRISTIAN CHURCH INC','BETHANY UNITED METHODIST CHURCH','BETHEL BAPTIST CHURCH',
                   'BIG FLATTS BAPTIST CHURCH','BLUE RIDGE MOUNTAIN CHURCH ASSOCIATION','BRISTOL BAPTIST CHURCH','BUFFALO MISSIONARY BAPTIST CHURCH','CALVARY FREE-WILL BAPTIST CHURCH','CALVARY FREEWILL BAPTIST CHURCH','CHURCH OF JESUS CHRIST TRUSTEES','CHURCH OF THE BRETHERN CAMP','COVENANT REFORMED CHURCH',
                   'CROSSNORE FIRST BAPTIST CHURCH','CROSSNORE PRESBYTERIAN CHURCH','EMMANUEL BAPTIST CHURCH','EMMANUEL BAPTIST CHURCH-TRUSTEES','FALL CREEK BAPTIST CHURCH','FIRST BAPTIST CHURCH - NEWLAND','FIRST BAPTIST CHURCH OF SPARTA TRUSTEES','FLETCHER MEMORIAL BAPTIST CHURCH','FRIENDLY GROVE BAPTIST CHURCH',
                   'FRIENDSHIP BAPTIST CHURCH OF','HEATON CHRISTIAN CHURCH','JEFFERSON UNITED METHODIST CHURCH','LAUREL KNOB BAPTIST CHURCH','LIBERTY GROVE BAPTIST CHURCH &','LIGHTHOUSE MISSIONARY BAPTIST CHURCH','MIDWAY BAPTIST CHURCH','MORAVIAN CHURCH','MORAVIAN CHURCH IN AMERICA SOUTHERN PROV',
                   'MOUNT CALVARY BAPTIST CHURCH','MT JEFFERSON BAPTIST CHURCH INC.','MT JEFFERSON PRESBYTERIAN CHURCH','MT PADDY CHURCH INC','MT. ZION UNITED METHODIST CHURCH OF ALLEGHANY','NEW HOPEWELL BAPTIST CHURCH','NEWLAND PRESBYTERIAN CHURCH','NORTH BEAVER BAPTIST CHURCH','OBIDS BAPTIST CHURCH',
                   'OLD FIELDS BAPTIST CHURCH -CECIL','PINEY RIDGE BAPTIST CHURCH','SEVENTH DAY ADVENT CHURCH','SHILOH UNITED METHODIST CHURCH','SMETHPORT BAPTIST CHURCH','SMETHPORT METHODIST CHURCH TRUSTEES','SOUTH BEAVER BAPTIST CHURCH','SOUTH FORK BAPTIST CHURCH &','SPARTA PRESBYTERIAN CHURCH',
                   'SPARTA UNITED METHODIST CHURCH','ST. FRANCIS CATHOLIC CHURCH','STONY HILL BAPTIST CHURCH','TUCKERDALE BAPTIST CHURCH','WEST JEFFERSON CHURCH OF CHRIST','WEST JEFFERSON METHODIST CHURCH','ZION METHODIST CHURCH','APPALACHIAN CHURCH INC','BAILEYS CAMP BAPTIST CHURCH','BALD MOUNTAIN BAPTIST CHURCH INC.',
                   'BALDWIN COMMUNITY CHURCH','BANNER ELK PRESBYTERIAN CHURCH','BEAVER CREEK CHRISTIAN CHURCH INC','BETHANY UNITED METHODIST CHURCH','BETHEL BAPTIST CHURCH','BIG FLATTS BAPTIST CHURCH','BLUE RIDGE MOUNTAIN CHURCH ASSOCIATION','BRISTOL BAPTIST CHURCH','BUFFALO MISSIONARY BAPTIST CHURCH',
                   'CALVARY FREE-WILL BAPTIST CHURCH','CALVARY FREEWILL BAPTIST CHURCH','CHURCH OF JESUS CHRIST TRUSTEES','CHURCH OF THE BRETHERN CAMP','CROSSNORE FIRST BAPTIST CHURCH','CROSSNORE PRESBYTERIAN CHURCH','EMMANUEL BAPTIST CHURCH','EMMANUEL BAPTIST CHURCH-TRUSTEES','FALL CREEK BAPTIST CHURCH',
                   'FIRST BAPTIST CHURCH - NEWLAND','FIRST BAPTIST CHURCH OF SPARTA TRUSTEES','FLETCHER MEMORIAL BAPTIST CHURCH','FRIENDLY GROVE BAPTIST CHURCH','FRIENDSHIP BAPTIST CHURCH OF','HEATON CHRISTIAN CHURCH','JEFFERSON UNITED METHODIST CHURCH','LAUREL KNOB BAPTIST CHURCH','LIBERTY GROVE BAPTIST CHURCH &',
                   'LIGHTHOUSE MISSIONARY BAPTIST CHURCH','MIDWAY BAPTIST CHURCH','MINNEAPOLIS BAPTIST CHURCH CHAMP YOUNG & DENNIS KING &','MORAVIAN CHURCH','MORAVIAN CHURCH IN AMERICA SOUTHERN PROV','MOUNT CALVARY BAPTIST CHURCH','MT JEFFERSON BAPTIST CHURCH INC.','MT JEFFERSON PRESBYTERIAN CHURCH',
                   'MT PADDY CHURCH INC','MT. ZION UNITED METHODIST CHURCH OF ALLEGHANY','NEW HOPEWELL BAPTIST CHURCH','NEWLAND PRESBYTERIAN CHURCH','NORTH BEAVER BAPTIST CHURCH','OBIDS BAPTIST CHURCH','OLD FIELDS BAPTIST CHURCH -CECIL','PINEY RIDGE BAPTIST CHURCH','PRUITT VIRGINIA CHURCH','SEVENTH DAY ADVENT CHURCH',
                   'SHILOH UNITED METHODIST CHURCH','SMETHPORT BAPTIST CHURCH','SMETHPORT METHODIST CHURCH TRUSTEES','SOUTH BEAVER BAPTIST CHURCH','SOUTH FORK BAPTIST CHURCH &','SPARTA PRESBYTERIAN CHURCH','SPARTA UNITED METHODIST CHURCH','ST. FRANCIS CATHOLIC CHURCH','STONY HILL BAPTIST CHURCH',
                   'TUCKERDALE BAPTIST CHURCH','UPCHURCH LEWIS MARVIN JR & BETTY DANIEL (TRUSTEES)','WEST JEFFERSON CHURCH OF CHRIST','WEST JEFFERSON METHODIST CHURCH','ZION METHODIST CHURCH','COUNTY OF AVERY','COUNTY OF AVERY, NORTH CAROLINA','AVERY COUNTY BOARD OF EDUCATION','COUNTY OF AVERY',
                   'COUNTY OF AVERY NORTH CAROLINA','ASHE COUNTY OF','ASHE FEDERAL BANK','COUNTY OF ASHE','ASHE COUNTY BOARD OF EDUCATION','ASHE COUNTY OF','ASHE COUNTY TRANSPORTATION AUTHORITY','ASHE COUNTY WILDLIFE CLUB INC','ASHE FEDERAL BANK','ASHE MEMORIAL HOSPITAL INC','CARTER COUNTY BANK','WILKES COMMUNITY COLLEGE',
                   'WILKES COMMUNITY COLLEGE', 'NORTH CAROLINA WILDLIFE COMMISSION', 'STATE OF NORTH CAROLINA', 'BALD MOUNTAIN TRUST THE (TRUSTEES)', 'NATURE CONSERVANCY, THE', 'THE NATURE CONSERVANCY', 'STATE OF NORTH CAROLINA C/O STATE PROPERTY OFFICE','STATE OF NORTH CAROLINA THE','THE THE STATE OF NORTH CAROLINA',
                   'RICHARDSON, H SMITH JR ET AL (TRUSTEES),BALD MTN TRUST','RICHARDSON, H SMITH TRUSTEES,RICHARDSON TESTAMENTARY TRUST','CHARLES A CANNON, JR. MEMORIAL HOSPITAL, INC', 'CROSSNORE SCHOOL INC', 'WAL-MART REAL ESTATE BUSINESS TRUST', "LOWE'S HOME CENTER INC", 'GRANDFATHER MOUNTAIN STEWARDSHIP FOUNDATION, INC',
                   'BANNER ELK, TOWN OF', 'TOWN OF BANNER ELK', 'LEES MC RAE COLLEGE FIXED ASSETS COORDINATOR', 'INGLES MARKETS INC', 'BOARD OF EDUCATION OF ALLEGHANY COUNTY', 'NATURE CONSERVANCY', 'VILLAGE OF SUGAR MOUNTAIN', 'BANNER ELK MEDICAL INVESTORS A TENN. LIMITED LIABILITY CO.', 'FIRST UNION NATIONAL BANK',
                   'AF BANK','BANK OF AMERICA NA,.NATIONSBANK NA','BLUE RIDGE BANK','CENTURA BANK','COMERICA BANK & TRUST, NA-TRUSTEE CAPASEE, LINDA C-TRUSTEE','FIFTH THIRD BANK','FIRST CITIZENS BANK & TRUST COMPANY','FIRST UNION NATIONAL BANK','FIRST UNION NATIONAL BANK,.MARY BOST C GRAY 1953 TRUST','HIGH COUNTRY BANK',
                   'HIGH POINT BANK & TRUST CO SUCCESSOR TR,THE T HENRY WILSON FAMILY TRUST','HIGH POINT BANK & TRUST CO TRUSTEE FOR T HENRY WILSON III','HIGHLANDS UNION BANK','LIFESTORE BANK','SKYLINE NATIONAL BANK','YADKIN VALLEY BANK & TRUST CO','YADKIN VALLEY BANK & TRUST COMPANY','WACHOVIA BANK NA,.JAMES M ATKINS IRREVOCABLE AGREEMENT',
                   'YADKIN BANK 3660 GLENWOOD AVE, STE 300', 'AVERY COUNTY, NC HUMANE SOCIETY, INC', 'STATE EMPLOYEES CREDIT UNION INC,BOONE BRANCH LOCATION',"STATE EMPLOYEES' CREDIT UNION", 'MAHARISHI UNIVERSITY OF ENLIGHTENMENT', "YOUNG MEN'S CHRISTIAN ASSOCIATION OF AVERY COUNTY",'PIONEER ECLIPSE CORPORATION','WEST JEFFERSON FIRST BAPTIST',
                   'JEFFERSON TOWN OF','BANNER ELK, TOWN OF','LANSING TOWN OF','NEWLAND, TOWN OF','TOWN OF BLOWING ROCK','TOWN OF SPARTA','WEST JEFFERSON TOWN OF','BANNER ELK, TOWN OF','JEFFERSON TOWN OF','LANSING TOWN OF','NEWLAND, TOWN OF', 'SUN FARMS INC', 'NORTH CAROLINA DEPARTMENT OF TRANSPORTATION', 'DOLLAR FARMS INC', 'STATE OF NC',
                   'OLEANDER COMPANY THE', 'CHESTER BAR OF NORTH CAROLINA', 'AVERY DEVELOPMENT CORPORATION', 'AVERY TIMBER RESOURCES, LLC 1/2 PHILLIPS, MARTHA ETAL 1/2', 'NATURE CONSERVANCY THE', 'BLUE RIDGE CONSERVANCY', 'NORTH CAROLINA STATE OF', 'NORTH CAROLINA WILDERNESS LTD', 'BANNER ELK LOWES LLC',
                   'LONE OAK CORPORATION', 'INN AT CRESTWOOD INC', 'LUTHERIDGE LUTHEROCK MINISTRY INC','SHOPPES OF TYNECASTLE, LLC', 'HALCORE GROUP INC.','ALLEGHANY WELLNESS CENTER, INC.', 'HOLSTON PRESBYTERY CAMP CORP','BOWER & JOHNSON CORP', 'CHARMING INNS OF BLOWING ROCK HILLWINDS', 'LANSING CHEMI-CON INC', 'ASHE SENIOR VILLAGE INC',
                   'GOODWILL INDUSTRIES OF NORTHWEST', 'CORNERSTONE CHRISTIAN FELLOWSHIP INC.', 'WILBERN REALTY & INVESTMENT CO', 'WEST JEFFERSON HOUSING PARTNERSHIP','CALDWELL REALTY & INVESTMENT', 'PROPERTIES FOR CHILDREN', 'SMITHS AEROSPACE COMPONENTS INC', 'HENDERSONVILLE HEALTH CARE FACILITY', 'LINVILLE LAND HARBORS PROPERTY OWNERS ASSOCIATION',
                   'ASHE SERVICES FOR AGING FOUNDATION', 'LEES MC RAE COLLEG, INC', 'BLUE RIDGE HOUSING OF ELK PARK', 'N C DEPT OF ADMIN FOREST SERVICE', 'SHOPPES OF TYNECASTLE,LLC', 'BLUE RIDGE ELECTRIC MEMBERSHIP CORPORATION', 'INGLES MARKETS INC # 83', 'WENTWORTH REALTY SERVICES, LLC','LEES MC RAE COLLEGE, INC','BANNER ELK LOWES, LLC',
                   'BLUE RIDGE HOUSING OF ASHE LLC','BJW 1 REALTY, LLC','BLOWING ROCK REALTY & INS INC','BLOWING ROCK REALTY INC','BROYHILL REALTY INC'  'CALDWELL REALTY','CASH REALTY LLC','DIAMOND REALTY PARTNERS IV LLC','DRG REALTY INC.','EUREY, KATHERINE E ET AL,IDEAL REALTY','M & T MOUNTAIN REALTY, LLC','MC MANUS & ASSOCIATES REALTY, LLC',
                   'MMW REALTY LLC','PRAGER REALTY III, LLC','WEST JEFFERSON REALTY LLC','WILBERN REALTY & INVESTMENT','GRIFFITH, E C CO REALTORS','SUGAR MOUNTAIN SKI RESORT, LLC','BLUE RIDGE CONSERVACY','SLOOP MEDICAL OFFICE PLAZA CONDOMINIUM ASSOC.','ABSHER, LOUISE WRIGHT GREENE LIFE ESTATE',
                   'BINGHAM, STACEY LIFE ESTATE,BINGHAM, REBA LIFE ESTATE','BURLESON, BETTY D LIFE ESTATE,CHURCH, SANDRA DAWN','BYRD, JOHNNY M LIFE ESTATE,BYRD, ELLA MAE LIFE ESTATE','CASTLE, BARBARA L, LIFE ESTATE','COFFEY, ALFRED JR-LIFE ESTATE COFFEY, WANDA-LIFE ESTATE','COOK, FRANKLIN D (LIFE ESTATE)','CORBETT, KENNETH LIFE ESTATE,CORBETT, SHIRLEY LIFE ESTATE',
                   'CORNETT, LEN AND BETTY (LIFE ESTATE)','CROWELL, CHARLES C JR LIFE ESTATE,CROWELL, ROBERTA LIFE ESTATE','DAVENPORT, HOWARD S LIFE ESTATE'  'DEMARAS, ELIZABETH-LIFE ESTATE','DRUCKER, A NORMAN LIFE ESTATE,DRUCKER, SHEILA LIFE ESTATE','EGGERS, MARTHA LIFE ESTATE','ERLANDER, JAMES C LIFE ESTATE,BL ROCK CHARITY HORSE SHOW FD',
                   'ESCHER, ROBERT E (LIFE ESTATE)','FLANAGAN, MARCELLA (LIFE ESTATE)','FRANTZEN, BERNHARD K LIFE EST,FRANTZEN, ANN LIFE ESTATE','GORE, GROVER , LIFE ESTATE,GORE, MARIANNE, LIFE ESTATE','GREENE, ALLEN HILL LIFE ESTATE,NORRIS, ANITA G','GREENE, KATE VANNOY LIFE ESTATE','GREER, JOSEPH DALE (LIFE ESTATE)','HADLY, MARY P LIFE ESTATE,HADLY, ROBERT BRUCE',
                   'HALL, ROGER F JR LIFE ESTATE','HILL, BONNIE KNIGHT LIFE ESTATE','HOLLARS, JAMES ROBERT LIFE ESTATE,HOLLARS, MAXINE LIFE ESTATE','HOLSHOUSER, REBECCA R (LIFE ESTATE)','JACKSON, JOHN R LIFE ESTATE,JACKSON, GLENDA LIFE ESTATE','JOHNSON, PAULINE D (LIFE ESTATE)','JOHNSON, R C LIFE ESTATE,JOHNSON, FAITH LIFE ESTATE','JONES, ANNELIESE LIFE ESTATE,JONES, MARKUS E AND STEFANIE V',
                   'KIRBY, ERIN LIFE ESTATE,HAMPTON, MARGOT LITE ESTATE','LYONS, JAMES F LIFE ESTATE,LYONS, IRMA B LIFE ESTATE','MARTHA ELROD EGGERS (LIFE ESTATE),CHARLES D EGGERS (LIFE ESTATE)','MAYO, JOYCE C LIFE ESTATE,MAYO, JOHN A III','MCNEELY, JOHN AND HAL (LIFE ESTATE),MCNEELY, MARSHA ET AL','MONTALDI, BARBARA LIFE ESTATE,MONTALDI, PETER','MOORE, IVEY (LIFE ESTATE),BUMGARNER, THELMA MARIE',
                   'MORETZ, REBA (LIFE ESTATE),MORETZ, JOHN B','MORGAN, VIRGIL LEE LIFE ESTATE','NANCY AND JAMES MELTON  LIFE ESTATE,HODGES, MICHAEL ALAN','PALMER, IVA LEE LIFE ESTATE,PALMER, SHERRY R','PETERSILIE, NATALIE BETH (LIFE ESTATE)','PETERSON, LYNN W LIFE ESTATE,AVANT, TRACY','PIPES, LENORE LIFE ESTATE,HARWOOD, YVETTE','RALPH AND RUBY BUFF LIFE ESTATE,LOFTIS, TERESA BUFF',
                   'RICHARDSON, DAVID (LIFE ESTATE),RICHARDSON, SHIRLEY P (LIFE ESTATE)','ROLLINS, MATTHEW FRED,TRIPLETT, PATRICIA H LIFE ESTATE','SCHOEL, HELEN R, LIFE ESTATE','SHERRILL, BOBBY LIFE ESTATE,SHERRILL, JOYCE LIFE ESTATE','SELLERS, GEORGE M, LIFE ESTATE','STORIE, MARVIN K,SIGMON, MARGARET E (LIFE ESTATE)','SUMMEY, WILLIAM C LIFE ESTATE,SUMMEY, JUDY LIFE ESTATE',
                   'TOWNSEND, TOM G (LIFE ESTATE)','TRIVETT, LUCY B-LIFE ESTATE','TURNER, CAROLE L LIFE ESTATE,TURNER, THOMAS WAYNE LIFE ESTATE','WHALEY, CLARA W LIFE ESTATE,WILSON, BENNIE M','WHEELER, EVA LIFE ESTATE,BROOKS, DENISE W','WYNNS, JOYCE C LIFE ESTATE,LORD, PAT','YOUNG, OWEN LIFE ESTATE,YOUNG, ROSA LIFE ESTATE','2014 RAMONA T PRESSON LIVING TRUST','ALAN W. SORRICK LIVING TRUST,JANE G. SORRICK LIVING TRUST',
                   'ALTER LIVING TRUST','ANDERSON JUDY B (LIVING TRUST)','ANGELO AND JENNIFER GIANNI LIVING TRUST,GIANNI, JENNIFER PAIGE \TR','ANNA W PHILLIPS LIVING TRUST','ANTHONY AND HEATHER LASALA LIVING TRUST','ANTHONY CHARLES NELSON AND WINIFRED,MAXINE NELSON LIVING TRUST AGREEMENT','ASHLEY H BAKER-FINLAY LIVING TRUST,BAKER-FINLAY, ASHLEY H','BABEN PATRICELLI LIVING TRUST',
                   'BARBARA C SUTTON LIVING TRUST,SUTTON, BARBARA C \TR','BARBARA GOTTSCHALK  LIVING TRUST','BARLOW LIVING TRUST,BARLOW, KENNETH D \TR','BEN A. FOX SR. LIVING TRUST,SHIRLEY F. FOX LIVING TRUST','BERRY LIVING TRUST','BETTY H GREENE LIVING TRUST','BEVERLY J STAHL REVOCABLE LIVING TRUST','BLANFORD BERNARD HODGSON JR LIVING TRUST','BOB E BAKER LIVING TRUST,BAKER, BOB E','BOBBY MCCONNELL LIVING TRUST,MCCONNELL, MARY, TRUSTEE',
                   'BOLES LIVING TRUST,BOLES, ROBERT J JR \TR','BRUNSON, EMMETT EVAN,.EMMETT EVAN BRUNSON LIVING TRUST','BULLINS LIVING TRUST','C TIANA PHILLIPS LIVING TRUST','CAMERON B ST CLAIR LIVING TRUST','CARL FIDLER LIVING TRUST,FIDLER, CARL','CARL R CRITCHER LIVING TRUST,CRITCHER, CARL R','CARLYLE ENGLAND LIVING TRUST,ENGLAND, CARLYLE','CAROL H ESSICK REVOCABLE LIVING TRUST',
                   'CAROL H HINSHAW LIVING TRUST,HINSHAW, CAROL H','CAROL THOMPSON LIVING TRUST','CELIA A. BOUTWELL LIVING TRUST','CHARLES L. DUMKE REVOCABLE LIVING TRUST,DUMKE, CHARLES L./TR','CHARLOTTE KELLY LIVING TRUST','CHERYL W CRAWFORD REVOCABLE LIVING TRUST,CRAWFORD, CHERYL W','CHESTER J KYLE, JR AND JANICE KIRBY KYLE,LIVING TRUST','CLARA S BARKER LIVING TRUST,BARKER, CLARA S',
                   'CLAYTON C DEAN LIVING TRUST,DEAN, CLAYTON C','CLEONE HODGES LIVING TRUST','COFFEY, BETTY M,.BETTY M COFFEY LIVING TRUST','CORNELL, JERI Z, TRUSTEE,JERI Z CORNELL LIVING TRUST','CRAMP PATRICIA A LIVING TRUST','DALTON FAMILY LIVING TRUST,DALTON, ARTHUR L JR \TR','DANIEL W MITCHUM LIVING TRUST,MITCHUM, DANIEL W','DARREN AND KIMBERLY LEWIS LIVING TRUST,LEWIS, DARREN V',
                   'DAVID HAAS LIVING TRUST,HAAS, DAVID','DENVER TAYLOR LIVING TRUST,TAYLOR, DENVER','DONALD AND MARTHA ERICKSON TRUST,LIVING TRUST AGREEMENT A REVOCABLE TRUST','DONALD TREINEN AND DENISE TREINEN,LIVING TRUST','DONNA R GLAZIER LIVING TRUST,GLAZIER, DONNA R','DORIT L TEETERS LIVING TRUST','DOROTHY J RENEAU FAMILY TRUST,ROBERT D RENEAU LIVING TRUST','E B FOX JR LIVING TRUST,EULA MAE FOX LIVING TRUST',
                   'EDGAR L JOINES LIVING TRUST','EDWARD H TREADWELL LIVING TRUST','EMILIO A PALOMO LIVING TRUST','EUGENIA D STONE LIVING TRUST','EVANS OLGA REVOC LIVING TRUST','FAYTHE R FURMAN LIVING TRUST,FURMAN, FAYTHE R','FINLEY HODGES LIVING TRUST,HODGES, FINLEY','FRANK & LORRAINE CLARKSON LIVING TRUST','FRED AND SUZANNE CLAVELLI LIVING TRUST,CLAVELLI, FRED A \TR','GCE 2008 REVOCABLE LIVING TRUST',
                   'GEORGE W COLCLOUGH LIVING TRUST,COLCLOUGH, GEORGE W \TR','GERRY W KELLER LIVING TRUST','GLENDA T HUBBARD LIVING TRUST','GLENN D ANDREWS, JR, LIVING TRUST','GLENN D COTTRELL LIVING TRUST','GLENN SUSAN LIVING TRUST','GLYNDA S. VALENTINE LIVING TRUST,BUMGARNER, MARK D. \TR','GREGORY M GRANA REVOCABLE LIVING TRUST,GRANA, GREGORY M \TR','GREGORY M HUFFMAN LIVING TRUST','HARRIET H KENNEDY REVOCABLE LIVING TRUST',
                   'HELEN IRVIN LIVING TRUST','HILL LIVING TRUST','HOYLE B COFFEY LIVING TRUST','JACK M. SIMS AND PAULA DOREEN SIMS,REVOCABLE LIVING TRUST','JAMES & LILA LOWE LIVING TRUST','JAMES C GOODNIGHT JR LIVING TRUST,GOODNIGHT, JAMES C JR','JAMES COKER FORT 2012 LIVING TRUST,FORT, JAMES COKER \TR','JAMES E CLABOUGH LIVING TRUST','JAMES H RUFF LIVING TRUST','JAMES H HODGES JR LIVING TRUST,HODGES, JAMES H JR',
                   'JAMES MARK ROBERTSON LIVING TRUST','JAMIE AND FRANK ALDRIDGE LIVING TRUST,ALDRIDGE, JAMIE BURKETT \TR','JANELLE R HAVNER LIVING TRUST','JARNDAL, BRITTA,.BRITTA JARNDAL REVOCABLE LIVING TRUST','JENNY SCOTT ELLERBE LIVING TRUST','JIMMIE NELL OWEN LIVING TRUST','JOEL R WHITE REVOCABLE LIVING TRUST','JOHN & BARBARA MORETZ LIVING TRUST,MORETZ, JOHN W','JOHN ANTHONY REEVES LIVING TRUST,JILL DINWIDDIE REEVES LIVING TRUST',
                   'JOHN ANTHONY REEVES LIVING TRUST,JILL DINWIDDIE REEVES LIVING TRUST','JOHN CZIPRI LIVING TRUST','JOHN D COOK LIVING TRUST,ROSE B COOK LIVING TRUST','JOHN DENNY SMITHERMAN SR DECLARATION,OF LIVING TRUST','JOHN M PAYNE LIVING TRUST,PHYLLIS T PAYNE LIVING TRUST','JOHN N STACY LIVING TRUST','JOHN R BURLINSON LIVING TRUST,BURLINSON, JOHN R','JOHN W. DAVIS AND BARBARA D. DAVIS,REVOCABLE LIVING TRUST',
                   'JOHNSON, NILA JEAN,.NILA JEAN JOHNSON LIVING TRUST','JOSEPH AND NANCY BELL JOINT LIVING TRUST,BELL, JOSEPH T II \TR','JOYCE FALK MASON REVOCABLE LIVING TRUST,MASON, JOYCE FALK \TR','KASSAB, ROB,.ROB KASSAB LIVING TRUST AGREEMENT','KATHERINE MCCRARY JOHNSON REVOCABLE,LIVING TRUST','KAY STACY LIVING TRUST','KENNETH E SCHRAM LIVING TRUST,SCHRAM, KENNETH E','KERMIT DREW SUMRELL/MARGO SHEETS SUMRELL,REVOCABLE LIVING TRUST',
                   'LARRY EDWIN MULL REVOCABLE LIVING TRUST,MULL, LARRY EDWIN (TR)','LAUTERBACH, ANN S,.ANN S LAUTERBACH LIVING TRUST','LARRY V ELLIS LIVING TRUST','LEETE LIVING TRUST','LEMLY MINNIE C (LIVING TRUST) (1/2)','LEON AND KAY MORETZ LIVING TRUST','LEON AND KAY MORETZ LIVING TRUST','LILLIAN TURCHIN LIVING TRUST','LIVING TRUST OF KAY DREW,DREW, WILLIS \TR','LOIS T HAYES LIVING TRUST,JOHNSON, CHERRY H',
                   'LORIN A BAUMHOVER LIVING TRUST','LOWMAN, JAMES G,.JAMES G LOWMAN REVOCABLE LIVING TRUST A','LYNN BRENNAN REVOCABLE LIVING TRUST','LYNN HOLCOMB MARTIN LIVING TRUST','LYNNE R SLASOR LIVING TRUST,SLASOR, LYNNE R','MAHLER, INGE H L,.INGE MAHLER REVOCABLE LIVING TRUST','MARGARET K SPARKS LIVING TRUST','MARJORIE HELEN WRIGHT LIVING TRUST','MARK E HARRILL LIVING TRUST,HARRILL, MARK E','MARK S HURST LIVING TRUST,HURST, MARK S',
                   'MARTIN, ANA,.ANA MARTIN LIVING TRUST','MARY ELIZABETH MCCONNELL LIVING TRUST,MCCONNELL, MARY ELIZABETH, TRUSTEE','MARY S HORN LIVING TRUST,HORN, MARY S TR','MAST, THELMA,.THELMA MAST LIVING TRUST','MASTERSON FAMILY LIVING TRUST','MELANIE B WILCOX LIVING TRUST,WILCOX, MELANIE B','MELANY D MCFALL LIVING TRUST','MELVIN R HODGES LIVING TRUST,MARGARET C HODGES LIVING TRUST','MICHAEL & LUCILLE MCGUIRE LIVING TRUST',
                   'MICHAEL M MILLER REVOCABLE LIVING TRUST','MINTZ, HOWARD, TRUSTEE,THE HOWARD MINTZ REVOCABLE LIVING TRUST','MOLLY F HUNDLEY LIVING TRUST','NORMA AND LARRY LIVING TRUST','OXFORD, BRUCE ALLEN,.BRUCE ALLEN OXFORD LIVING TRUST','P SANDRA KADYK LIVING TRUST,KADYK, J MARC','PAGE PREWITT LIVING TRUST,PREWITT, PAGE','PAIGE R MURRAY LIVING TRUST,MABEL MURRAY LIVING TRUST','PALMA KOGER LIVING TRUST,KOGER, PALMA',
                   'PARSONS REVOCABLE LIVING TRUST,PARSONS, ERIC STEPHEN \TR','PATRICIA QUICK BECK 2013 LIVING TRUST,BECK, PATRICIA QUICK \TR','PAUL & JEANNIE KEASEY LIVING TRUST,KEASEY, JEANNIE P TRUSTEE','PERRY LIVING TRUST','PIETAN, MARY F. \TR,MARY F. PIETAN LIVING TRUST','PAULETTE PLAYCE REVOCABLE LIVING TRUST,PLAYCE, PAULETTE \TR','POTTER LIVING TRUST','RAEFORD RUSSELL LIVING TRUST','RAYMOND ANDREW WHITE LIVING TRUST',
                   'RAYMOND P HOWELL LIVING TRUST','REBECCA A LOVERN LIVING TRUST','REBECCA J KEETER LIVING TRUST','REBECCA W SHIPPY LIVING TRUST','REVOCABLE LIVING TRUST OF SUZANNE T,PURRINGTON','RICE, MARTHA R,MARTHA R RICE LIVING TRUST','RICHARD G MCGUIRE LIVING TRUST','RICHARD MATHIAS AND DONNA MATHIAS,LIVING TRUST','RICHARD W WINKLER LIVING TRUST','ROBERT F PLANE JR LIVING TRUST,PLANE, ROBERT F JR','ROBERT FRANCIS PAYNE AND SUSAN MARCH,PAYNE JOINT LIVING TRUST',
                   'ROD A SMITH LIVING TRUST,LESLIE W JOYCE LIVING TRUST','ROESNER LIVING TRUST','RONALD J STANLEY LIVING TRUST','RONNIE G WILSON LIVING TRUST,WILSON, RONNIE G','ROSE BRIDGEMAN LIVING TRUST','RUPP, MARY G, TRUSTEE,MARY G RUPP LIVING TRUST','RUTH W COOK LIVING TRUST,COOK, RUTH W','SALLY HICKERNELL OVERPECK LIVING TRUST,OVERPECK, SALLY HICKERNELL \TR','SAM M ADAMS LIVING TRUST,ADAMS, SAM M \TR',
                   'SANCHEZ, DOLORES MARIA,.DOLORES MARIA SANCHEZ LIVING TRUST','SANDA LEACH COOPER LIVING TRUST','SANDRA JEAN GLOVER LIVING TRUST','SANDRA M. HAYES LIVING TRUST,SANDRA M. AND ANTHONY J. HAYES, TRUSTEES','SANZARI LIVING TRUST','SCOTT, JANE R,.JR SCOTT LIVING TRUST','SEAWELL LIVING TRUST','SHARON L PITTS REVOCABLE LIVING TRUST,PITTS, SHARON L \TR','SIBYL WHITE PRESSLY LIVING TRUST,PRESSLY, SIBYL W',
                   'STAGNER LIVING TRUST','STEPHEN AND PATRICIA GREENE LIVING TRUST','STEPHEN G PHILLIPS LIVING TRUST','STEVE & LINDA RIGELL LIVING TRUST,RIGELL, STEVE','STORELLI FAMILY REVOCABLE LIVING TRUST,STORELLI, JILL K \TR','SUSAN C HALL LIVING TRUST,HALL, SUSAN C','SUSAN E KEEFE LIVING TRUST,KEEFE, SUSAN E \TR','SUSAN GLENN LIVING TRUST,GLENN, SUSAN','SUSAN PITTS LIVING TRUST,PITTS, SUSAN',
                   'TERRENCE W REIGEL LIVING TRUST,NANCY F REIGEL LIVING TRUST','TERRI B WALLER LIVING TRUST,WALLER, TERRI B','THE ARCHER LIVING TRUST','THE ARTHUR A SELBY, JR LIVING TRUST','THE CHERYL S STANLEY LIVING TRUST','THE E & M PIDERMANN LIVING TRUST,PIDERMANN, MARTHA M. \TR','THE JON CAMILLE ALEXANDER LIVING TRUST,ALEXANDER, JON CAMILLE \TR','THE POLLY PURGASON LIVING TRUST,PURGASON, POLLY TTEE',
                   'THE POTTER LIVING TRUST','THE SUSAN D ROBERTSON LIVING TRUST','THE SUSAN PAULETTE DALE,REVOCABLE LIVING TRUST','THE SUZANNE M. GUERIN REVOCABLE,LIVING TRUST','THOMAS M CRITCHER LIVING TRUST','THOMAS R MALLARD AMENDED AND RESTATED,LIVING TRUST AGREEMENT','THOMAS, JOHN E AND JANICE P,JANICE P THOMAS LIVING TRUST','TIMOTHY P DYE AND KARLA DYE,REVOCABLE LIVING TRUST','TRIPLETT, JIM W,.JIMMY W TRIPLETT LIVING TRUST',
                   'VANARTHOS LIVING TRUST','VIRGINIA H. SIGMON,REVOCABLE LIVING TRUST','WALDREP, LYNDA B,.2007 LYNDA B WALDREP LIVING TRUST','WARNER, CARIN L,.2000 CARIN L WARNER LIVING TRUST','WATERS, JOANNE, TRUSTEE,ALBERT C WATERS LIVING TRUST','WATERS, JOANNE, TRUSTEE,JOANNE WATERS LIVING TRUST','WELLS, BETTY CLAWSON,.BETTY CLAWSON WELLS LIVING TRUST','WHITENER, CARR C, TRUSTEE,CARR C. WHITENER REVOCABLE LIVING TRUST',
                   'WILLA JEAN BROWN LIVING TRUST,BROWN, WILLA JEAN \TR','WILLIAM C WOLFF LIVING TRUST,WOLFF, WILLIAM C','WILLIAM DENNIS COOK LIVING TRUST','WILLIAM E MILLER LIVING TRUST,MILLER, WILLIAM E','WILLIAM FRANCES PRESSLY LIVING TRUST,PRESSLY, W FRANCIS','WILLIAM STEWART PENICK LIVING TRUST,PENICK, STEWART','WOODROW LIVING TRUST','WRIGHT, JOHN RICHARD,.JOHN RICHARD WRIGHT LIVING TRUST',
                   'ADAMS BOBBY F  (L/E) & WILLIAM D','ASHLEY WO JR & PEARL J (L/E);','BARE HAZEL (L/E)','BARE LARRY J (L/E)','BEDSAUL, CLINT F. & LINDA T. L/E','BENNETT GALE F (L/E)','BLEVINS ROGER (L/E)','BOOTH LARRY D (L/E)','BROWN ANNIE W (L/E)','CALLOWAY MARY H (L/E)','CARABALLO, SILVIA C. L/E','CHEEK FRANCIS (L/E)','CHURCH BILLY D & LINDA C (L/E)','COX, JAMES MATHEWS L/E','CROUSE, BRONDA M. L/E','DICKENS R EDWIN (L/E)',
                   'ELDRETH MANNON (L/E)','ELLER JEAN (L/E)','ELLIS CHARLES L (L/E)','ELLISON JAMES W & BRENDA E (L/E)','GOMEZ SARA C (L/E)','GREENE HATTIE JO (L/E)','HODGSON DAVID  (L/E)','HOPKINS SYLVIA (L/E)','HOWELL GALE DEAN & ELEANOR (L/E)','JOHNSON LAWRENCE & ANITA L (L/E)','JOINES, KATHRYN L/E','JONES JIMMY LEE & DEBORAH S (L/E)','JONES SHIRLEY M (L/E)','JORDAN REX & SUE (L/E)','LINEBERGER JASON R & LIDA C (L/E)',
                   'LITTLE KATHLEEN (L/E)','MILLER BERNARD (L/E)','MILLER BILLY RAY & BETTY (L/E)','MILLER GRACE S (L/E)','MILLER GRACE S (L/E)','MILLER JAMES W & SHIRLEY S (L/E)','MILLER ROBERT W (L/E)','OSBORNE, REBA K. L/E','PHILLIPS CARL H & HELEN (L/E)','PHILLIPS DARRELL Q (L/E)','RHODES LENA S (L/E)','SEVERT AUDREY (L/E)','SEVERT REX ALLEN & PATRICIA P (L/E)','SNYDER CORENA (L/E)','TURNER MABEL (L/E)','VANNOY WILLIAM F & NANCY (L/E)',
                   'WADDELL FRED Y (L/E)','WOODIE THOMAS C & MARY LOU (L/E)','YIENGST THEODORE & ROSEMARY (L/E)']


#drop rows with these ownname from homes_df
for owner_name in bad_owner_names:
    homes_df.drop(homes_df[homes_df['ownname'] == owner_name].index, inplace=True)
#drops 855 parcels. Down to 128528 parcels



#export homes_df into shapefile for use in postgreSQL
homes_df = gpd.GeoDataFrame(homes_df, geometry='geometry')
homes_df.to_file('/Users/ep9k/Desktop/homes_df.shp')


print('Done!')
